/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as AuthAuthImport } from './routes/_auth/_auth'
import { Route as AuthAuthRegisterImport } from './routes/_auth/_auth.register'
import { Route as AuthAuthPaymentHistoryImport } from './routes/_auth/_auth.payment-history'
import { Route as AuthAuthPaymentImport } from './routes/_auth/_auth.payment'
import { Route as AuthAuthMembershipPlansImport } from './routes/_auth/_auth.membership-plans'
import { Route as AuthAuthMembersImport } from './routes/_auth/_auth.members'
import { Route as AuthAuthCheckInImport } from './routes/_auth/_auth.check-in'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRegisterRoute = AuthAuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthPaymentHistoryRoute = AuthAuthPaymentHistoryImport.update({
  path: '/payment-history',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthPaymentRoute = AuthAuthPaymentImport.update({
  path: '/payment',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthMembershipPlansRoute = AuthAuthMembershipPlansImport.update({
  path: '/membership-plans',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthMembersRoute = AuthAuthMembersImport.update({
  path: '/members',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthCheckInRoute = AuthAuthCheckInImport.update({
  path: '/check-in',
  getParentRoute: () => AuthAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_auth': {
      id: '/_auth/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_auth/check-in': {
      id: '/_auth/_auth/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthAuthCheckInImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/members': {
      id: '/_auth/_auth/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthAuthMembersImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/membership-plans': {
      id: '/_auth/_auth/membership-plans'
      path: '/membership-plans'
      fullPath: '/membership-plans'
      preLoaderRoute: typeof AuthAuthMembershipPlansImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/payment': {
      id: '/_auth/_auth/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AuthAuthPaymentImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/payment-history': {
      id: '/_auth/_auth/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof AuthAuthPaymentHistoryImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/register': {
      id: '/_auth/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthAuthRegisterImport
      parentRoute: typeof AuthAuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  AuthAuthRoute: AuthAuthRoute.addChildren({
    AuthAuthCheckInRoute,
    AuthAuthMembersRoute,
    AuthAuthMembershipPlansRoute,
    AuthAuthPaymentRoute,
    AuthAuthPaymentHistoryRoute,
    AuthAuthRegisterRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/_auth/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/_auth": {
      "filePath": "_auth/_auth.tsx",
      "children": [
        "/_auth/_auth/check-in",
        "/_auth/_auth/members",
        "/_auth/_auth/membership-plans",
        "/_auth/_auth/payment",
        "/_auth/_auth/payment-history",
        "/_auth/_auth/register"
      ]
    },
    "/_auth/_auth/check-in": {
      "filePath": "_auth/_auth.check-in.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/members": {
      "filePath": "_auth/_auth.members.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/membership-plans": {
      "filePath": "_auth/_auth.membership-plans.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/payment": {
      "filePath": "_auth/_auth.payment.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/payment-history": {
      "filePath": "_auth/_auth.payment-history.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/register": {
      "filePath": "_auth/_auth.register.tsx",
      "parent": "/_auth/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
